name: build pyjava
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1,16 * *"
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - ".github/**"
permissions:
  actions: read
  packages: write
  contents: read
jobs:
  push:
    name: "Build: Python ${{ matrix.python_version }}, Java ${{ matrix.java_version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - '3.10'
          - '3.11'
          - '3.12'
        java_version:
          - '21'

    steps:
      - uses: actions/checkout@v4

      - name: Setup QEMU for multiarch build
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to registry
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          build-args: |
            PYTHON_VERSION=${{ matrix.python_version }}
            JAVA_VERSION=${{ matrix.java_version }}
          tags: ghcr.io/zingyawesome/pyjava:${{ matrix.python_version }}-${{ matrix.java_version }}
          push: true
